Padrão REST
danielveigasilva/APIPortalCEFET pull request #7
Opened 2020-02-07 05:03 UTC by thallesdella

Esse pull requesta da um fix #5 . 
Ele faz a API começara se encaixar no padrão REST.

2020-02-07 13:11 UTC, danielveigasilva commented on APIPortalCEFET.py
> +@app.route('/perfil/dados', methods=['GET'])
Conflito com a rota descrita na **linha 117**
Mudar rota para: ```perfil/geral```

2020-02-07 13:13 UTC, danielveigasilva commented on APIPortalCEFET.py
> +@app.route('/relatorio', methods=['GET'])
Mudar rota para: ```relatorio/extracao``` afim de manter o padrão seguido nas funções de perfil.

2020-02-07 13:14 UTC, danielveigasilva commented on APIPortalCEFET.py
> +@app.route('/relatorios', methods=['GET'])
Mudar rota para: ```relatorio/lista``` afim de manter o padrão seguido nas funções de perfil.

2020-02-07 13:16 UTC, danielveigasilva commented on APIPortalCEFET.py
> +def respond404():
Alterar para: ```def respond404(self):```

Para evitar erro: **respond404() takes 0 positional arguments but 1 was given**.

2020-02-07 13:22 UTC, danielveigasilva requested changes
Muito obrigado pela contribuição!
Fiz alguns pequenos comentários no código indicando modificações antes do merge.

2020-02-07 17:18 UTC, thallesdella commented
O padrão REST nao "permite" colocar a ação depois da rota como  "relatorio/lista". Isso ja viria pelo verbo HTTP tipo GET. 

GET -> Obter -> Lista
POST -> Cria
PUT -> Atualizar
DELETE -> Excluir

2020-02-07 17:37 UTC, thallesdella commented on APIPortalCEFET.py
> +@app.route('/relatorio', methods=['GET'])
O padrão REST nao "permite" colocar a ação depois da rota como "relatorio/extracao". Isso ja viria pelo verbo HTTP tipo GET.

2020-02-07 17:37 UTC, thallesdella commented on APIPortalCEFET.py
> +@app.route('/relatorios', methods=['GET'])
O padrão REST nao "permite" colocar a ação depois da rota como "relatorio/lista". Isso ja viria pelo verbo HTTP tipo GET.
O ideal seria colocar relatorios, na intenção de obter dados sobre relatorios

2020-02-07 17:37 UTC, thallesdella commented on APIPortalCEFET.py
> +@app.route('/perfil/dados', methods=['GET'])
Acho que fica mais claro se o outro a outra rota receber `perfil/geral` e essa receber `perfil`. 
Quando eu leio me passa a impressão que esse seria mais completo que o outro.

2020-02-07 20:06 UTC, danielveigasilva commented on APIPortalCEFET.py
> +@app.route('/perfil/dados', methods=['GET'])
Concordo, vamos proceder assim então.

2020-02-07 20:16 UTC, danielveigasilva commented on APIPortalCEFET.py
> +@app.route('/relatorio', methods=['GET'])
Entendi, poderiamos fazer algo como ``` /relatorios/pdf``` ou ``` /relatorios/relatorio```  para a extração? mantendo a listagem como você fez: ```/relatorios/```. Pois me parece estranho a rota para um arquivo de relatório estar fora do caminho do próprio "relatórios".

2020-02-07 20:18 UTC, danielveigasilva commented on APIPortalCEFET.py
> +@app.route('/relatorios', methods=['GET'])
Entendi, poderiamos fazer algo como /relatorios/pdf ou /relatorios/relatorio para a extração? mantendo a listagem como você fez: /relatorios. Pois me parece estranho a rota para um arquivo de relatório estar fora do caminho do próprio "relatórios".

2020-02-07 20:25 UTC, danielveigasilva commented
Em complemento aos comentários anteriores: 
Agradeço os esclarecimentos referentes ao padrão REST :smiley:, ainda estou estudando as boas práticas. 
Teria algum material que recomendaria para o estudo? Seria de grande ajuda :grin:.

2020-02-07 20:57 UTC, thallesdella commented
Fiz as correções, depois de uma olhada.
Segue uns links falando um pouco sobre o padrão REST.
https://sensedia.com/api/design-de-api-rest/
https://becode.com.br/o-que-e-api-rest-e-restful/

2020-02-13 23:07 UTC, danielveigasilva commented
Agradeço as contribuições! Estou realizando o merge.

2020-02-13 23:08 UTC, merged